
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: articlecomm_development


test:
  <<: *default
  database: articlecomm_test

production:
  <<: *default
  database: articlecomm_production
  username: articlecomm
  password: <%= ENV['ARTICLECOMM_DATABASE_PASSWORD'] %>
