# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08c992074d03da384f9f6784acd6d86b038c0b266eb1f0049090fe21e1097333d0d07cd2c4267776139304ad6ff01a2f738930217bd828042384011bcac42c0

test:
  secret_key_base: 16e0c50b61748e1cc928f0c5f32c0c7cb9fd1650c90321a83631184631c15daa4fc209649d479f23dfadc349a17c3df74604466b1545b0a64c7e1cf41bda9c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
